# Generated by Django 5.1.4 on 2025-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=50, verbose_name='نام مشتری')),
                ('user_phone_number', models.CharField(max_length=13, verbose_name='شماره تلفن')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('user_nationalcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی')),
                ('order_number', models.CharField(max_length=18, unique=True, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغو شده'), ('waiting_approval', 'در انتظار تایید (کارت به کارت)')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_price', models.IntegerField(default=0, verbose_name='قیمت نهایی ')),
                ('paid_price', models.IntegerField(blank=True, null=True, verbose_name='مبلغ قابل پرداخت')),
                ('payment_method', models.CharField(choices=[('gateway', 'درگاه بانکی'), ('manual', 'کارت به کارت')], max_length=20, verbose_name='نحوه پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('address_address', models.TextField(verbose_name='ادرس')),
                ('address_province', models.CharField(max_length=100, verbose_name='استان')),
                ('address_city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address_postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100, verbose_name='نام گزینه')),
                ('option_value', models.CharField(max_length=100, verbose_name='مقدار گزینه')),
                ('Price_increase', models.PositiveBigIntegerField(verbose_name='اضافه قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='OrderShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام روش ارسال')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه ارسال (تومان)')),
                ('is_postpaid', models.BooleanField(default=False, verbose_name='پس\u200cکرایه (هزینه با مشتری)')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('gateway', 'درگاه بانکی'), ('manual', 'کارت به کارت')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام روش ارسال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shipping_logos/', verbose_name='لوگو')),
                ('is_postpaid', models.BooleanField(default=False, verbose_name='پس\u200cکرایه (هزینه با مشتری)')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه ارسال')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.PositiveIntegerField(verbose_name='هزینه پایه (تومان)')),
                ('max_weight_kg', models.PositiveIntegerField(verbose_name='حداکثر وزن مجاز (کیلوگرم)')),
                ('price_per_extra_kg', models.PositiveIntegerField(default=0, verbose_name='هزینه هر کیلوگرم اضافه (تومان)')),
                ('estimated_delivery_days', models.PositiveIntegerField(verbose_name='زمان تحویل تخمینی (روز)')),
            ],
            options={
                'verbose_name': 'هزینه ارسال',
                'verbose_name_plural': 'هزینه\u200cهای ارسال',
                'ordering': ['method', 'max_weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, verbose_name='نام محدوده')),
                ('cities', models.TextField(verbose_name='شهرهای تحت پوشش')),
            ],
            options={
                'verbose_name': 'محدوده ارسال',
                'verbose_name_plural': 'محدوده\u200cهای ارسال',
            },
        ),
    ]
