# Generated by Django 5.1.4 on 2025-07-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغو شده'), ('waiting_approval', 'در انتظار تایید (کارت به کارت)')], default='pending', max_length=20),
        ),
    ]
