# Generated by Django 5.1.4 on 2025-07-22 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_order_status_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartnumber',
            options={'verbose_name': 'شماره کارت', 'verbose_name_plural': 'شماره\u200cهای کارت'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderitemoption',
            options={'verbose_name': 'گزینه آیتم سفارش', 'verbose_name_plural': 'گزینه\u200cهای آیتم سفارش'},
        ),
        migrations.AlterModelOptions(
            name='ordershippingmethod',
            options={'verbose_name': 'روش ارسال سفارش', 'verbose_name_plural': 'روش\u200cهای ارسال سفارش'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterField(
            model_name='cartnumber',
            name='available',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='cartnumber',
            name='cart_name',
            field=models.CharField(max_length=50, verbose_name='نام سبد'),
        ),
        migrations.AlterField(
            model_name='cartnumber',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره سبد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='payments.orderitem', verbose_name='آیتم سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.cartnumber', verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش درگاه'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('gateway', 'درگاه بانکی'), ('manual', 'کارت به کارت')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='تصویر رسید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده'), ('waiting_approval', 'در انتظار تایید (کارت به کارت)')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
