# Generated by Django 5.1.4 on 2025-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_cartnumber_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartnumber',
            name='cart_name',
            field=models.CharField(max_length=50, verbose_name='نام کارت'),
        ),
        migrations.AlterField(
            model_name='cartnumber',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره کارت'),
        ),
    ]
