# Generated by Django 5.1.4 on 2025-07-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_cartnumber_cart_name_alter_cartnumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartnumber',
            name='bank_name',
            field=models.CharField(default='x', max_length=20, verbose_name='نام بانک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartnumber',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='شماره کارت'),
        ),
    ]
