# Generated by Django 5.1.4 on 2025-07-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_cartnumber_bank_name_alter_cartnumber_number'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='cartnumber',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='شماره کارت'),
        ),
    ]
