# Generated by Django 5.1.4 on 2025-07-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_cartnumber_number'),
        ('payments', '0010_cartnumber_bank_name_alter_cartnumber_number'),
    ]

    operations = [
    ]
