# Generated by Django 4.2.11 on 2025-08-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_merge_20250723_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=700, verbose_name='نام محصول'),
        ),
    ]
