# Generated by Django 4.2.11 on 2025-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartnumber',
            name='sheba_number',
            field=models.CharField(blank=True, help_text='شماره شبا 24 رقمی', max_length=26, null=True, verbose_name='شماره شبا'),
        ),
    ]
