# Generated by Django 5.1.4 on 2025-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to='products.product'),
        ),
    ]
