# Generated by Django 5.1.4 on 2025-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, verbose_name='زمان مطالعه'),
            preserve_default=False,
        ),
    ]
