"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# مقداردهی اولیه django-environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])




# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'formtools',
    'common.apps.CommonConfig',  # اپلیکیشن‌های عمومی
    'home.apps.HomeConfig', # صفحه اصلی 
    'users.apps.UsersConfig',  # مدیریت کاربران
    'otp_auth.apps.OtpAuthConfig',  # ارسال و تأیید رمز یکبار مصرف
    'products.apps.ProductsConfig',  # مدیریت محصولات
    'carts.apps.CartsConfig',  # مدیریت سفارشات
    'payments.apps.PaymentsConfig',  # مدیریت پرداخت‌ها
    'blog.apps.BlogConfig',  # مقالات و اخبار
    'cms.apps.CmsConfig',  # مدیریت صفحات داینامیک
    'notifications.apps.NotificationsConfig',  # ارسال پیامک و نوتیفیکیشن‌ها
    'categories.apps.CategoriesConfig',  # مدیریت دسته‌بندی‌ها
    # اضافی
    'support.apps.SupportConfig',  # سیستم تیکت و پشتیبانی
    'discounts.apps.DiscountsConfig',  # سیستم تخفیف و کوپن
    # اپ های اضافی
    "django_ckeditor_5",
    'django_extensions',
    'taggit',
    'mptt',
    'auditlog',
    'debug_toolbar',
    'import_export',
    'django_admin_listfilter_dropdown',
    'rangefilter',
    'admin_auto_filters',
    'meta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # برای ثبت تغییرات
    'auditlog.middleware.AuditlogMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # برای محدودیت تعداد درخواست‌ها
    'main.middleware.GlobalRateLimitMiddleware',
]

INTERNAL_IPS = ['127.0.0.1']
ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.global_context',
            ],
            'libraries': {
                'main_filters' : 'main.templatetags.global_filters',
            },
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# یسری دیتا برای تنظیمات
ADMIN_PHONE = str(env("ADMIN_PHONE"))
# تنظیمات SMS.ir
SMSIR_API_KEY = str(env("SMSIR_API_KEY"))  # کلید API از پنل
SMSIR_LINE_NUMBER = str(env("SMSIR_LINE_NUMBER"))  # شماره خط ارسال
SMSIR_VERIFY_TEMPLATE_ID = str(env("SMSIR_VERIFY_TEMPLATE_ID"))  # شناسه قالب تأیید



# اجازه استفاده از یونیکد در SlugField
SLUGIFY_ALLOW_UNICODE = True

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.User'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/users/login'  

TAILWIND_APP_NAME = 'theme'

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

#پرداخت
SANDBOX = True
MERCHANT = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',  # مسیر دلخواه برای ذخیره فایل‌ها
    }
}

# تنظیمات سفارشی برای کش‌های شرطی
UPDATE_NEW_PRODUCTS = True
ENABLE_NEWSLETTER = True

'''
#arvan

AWS_ACCESS_KEY_ID = "a1f9f508-35a9-4ba0-9504-5a0934602b09"
AWS_SECRET_ACCESS_KEY = "25745f7d9a797555c3af37dd019821a69a596e851d6626256c1b5d92884c4d36"  # یادت باشه این مقدار رو از محیط امن‌تر بگیری
AWS_STORAGE_BUCKET_NAME = 'mediames'
AWS_S3_ENDPOINT_URL = "https://s3.ir-thr-at1.arvanstorage.ir"
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.ir-thr-at1.arvanstorage.ir"
AWS_S3_FILE_OVERWRITE = False

# ذخیره فایل‌های مدیا در آروان
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
'''

# CKEditor 5 Configuration
# settings.py

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "|",
            "link", "imageUpload", "codeBlock", "mediaEmbed", "|",
            "bulletedList", "numberedList", "|",
            "blockQuote", "insertTable", "|",
            "undo", "redo"
        ],
        "language": "fa",
    }
}

# For file uploads
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# تنظیمات پیشفرض برای محدودیت تعداد درخواست‌ها
GLOBAL_RATE_LIMIT = {
    'RATE_LIMIT': 100000,  # 100 درخواست
    'TIME_WINDOW': 60 , 
}

# لاگ گیری
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # لاگرهای دیگر جنگو غیرفعال نشوند
    'handlers': {
        'file': {
            'level': 'DEBUG',  # سطح لاگ‌گیری (از DEBUG به بالا)
            'class': 'logging.FileHandler',
            'filename': 'debug.log',  # فایلی که لاگ‌ها ذخیره می‌شوند
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',  # نمایش لاگ در ترمینال
        },
    },
    'loggers': {
        'django': {  # لاگ‌های مربوط به خود جنگو
            'handlers': ['file', 'console'],
            'level': 'INFO',
        },
        'myapp': {  # لاگ‌های مربوط به اپلیکیشن شما (نام اپ را جایگزین کنید)
            'handlers': ['file', 'console'],
            'level': 'DEBUG',  # تمام لاگ‌های DEBUG و بالاتر را ذخیره می‌کند
            'propagate': False,  # اجازه نده لاگ‌ها به والد (django) بروند
        },
    },
}