# Generated by Django 5.1.4 on 2025-07-22 16:10

import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'آپشن', 'verbose_name_plural': 'آپشن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='optiontype',
            options={'verbose_name': 'نوع آپشن', 'verbose_name_plural': 'انواع آپشن'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'مقدار ویژگی محصول', 'verbose_name_plural': 'مقادیر ویژگی محصول'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'آپشن محصول', 'verbose_name_plural': 'آپشن\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'تنوع محصول', 'verbose_name_plural': 'تنوع محصولات'},
        ),
        migrations.AlterField(
            model_name='option',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='option',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان (روز)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام آپشن'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.optiontype', verbose_name='نوع آپشن'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='optiontype',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='optiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام نوع آپشن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_file',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/', verbose_name='فایل کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف\u200cخورده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='need_to_call',
            field=models.BooleanField(default=False, verbose_name='نیاز به تماس دارد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروخته شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.attribute', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoption', to='products.option', verbose_name='آپشن'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='available',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.CharField(max_length=100, verbose_name='مقدار'),
        ),
    ]
