# Generated by Django 5.1.4 on 2025-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='لوگو')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس دفتر')),
                ('social_links', models.JSONField(blank=True, null=True, verbose_name='لینک شبکه\u200cهای اجتماعی')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255, verbose_name='عنوان سایت')),
                ('meta_description', models.TextField(verbose_name='توضیحات متا')),
                ('favicon', models.ImageField(upload_to='favicons/', verbose_name='فاوآیکون')),
                ('footer_text', models.TextField(verbose_name='متن فوتر')),
            ],
            options={
                'verbose_name': 'تنظیمات کلی سایت',
                'verbose_name_plural': 'تنظیمات کلی سایت',
            },
        ),
    ]
