# Generated by Django 5.1.4 on 2025-07-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='social_links',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='کد نقشه گوگل', null=True, verbose_name=' نقشه'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='توییتر'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
