# Generated by Django 4.2.11 on 2025-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_companyinfo_social_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن اضافی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شماره تلفن اضافی',
                'verbose_name_plural': 'شماره\u200cهای تلفن اضافی',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='home/slider/', verbose_name='تصویر')),
                ('button_text', models.CharField(default='اکنون خرید کنید', max_length=50, verbose_name='متن دکمه')),
                ('button_url', models.CharField(default='/', max_length=200, verbose_name='لینک دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'اسلایدر اصلی',
                'verbose_name_plural': 'اسلایدرهای اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('large', 'کارت بزرگ'), ('medium', 'کارت متوسط'), ('small', 'کارت کوچک')], max_length=10, verbose_name='نوع کارت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیرعنوان')),
                ('price_text', models.CharField(blank=True, max_length=50, verbose_name='متن قیمت')),
                ('image', models.ImageField(upload_to='home/promo/', verbose_name='تصویر')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'کارت تبلیغاتی',
                'verbose_name_plural': 'کارت\u200cهای تبلیغاتی',
                'ordering': ['order'],
            },
        ),
    ]
