# Generated by Django 4.2.11 on 2025-08-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraphone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
