# Generated by Django 4.2.11 on 2025-08-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_extraphone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraphone',
            name='description',
            field=models.CharField(default='d', max_length=100, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
