# Generated by Django 4.2.11 on 2025-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_extraphone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت'),
        ),
    ]
