# Generated by Django 4.2.11 on 2025-09-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_partner_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='button_text_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ متن دکمه'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='subtitle_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ زیرعنوان'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='subtitle_font_size',
            field=models.PositiveIntegerField(default=12, help_text='اندازه فونت به پیکسل', verbose_name='اندازه فونت زیرعنوان'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='text_position',
            field=models.CharField(choices=[('top-left', 'بالا چپ'), ('top-center', 'بالا وسط'), ('top-right', 'بالا راست'), ('center-left', 'وسط چپ'), ('center', 'وسط'), ('center-right', 'وسط راست'), ('bottom-left', 'پایین چپ'), ('bottom-center', 'پایین وسط'), ('bottom-right', 'پایین راست')], default='center', max_length=20, verbose_name='موقعیت متن'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ عنوان'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_font_size',
            field=models.PositiveIntegerField(default=35, help_text='اندازه فونت به پیکسل', verbose_name='اندازه فونت عنوان'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='button_text_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ متن دکمه'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='price_font_size',
            field=models.PositiveIntegerField(default=13, help_text='اندازه فونت به پیکسل', verbose_name='اندازه فونت قیمت'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='price_text_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ متن قیمت'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='subtitle_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ زیرعنوان'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='subtitle_font_size',
            field=models.PositiveIntegerField(default=13, help_text='اندازه فونت به پیکسل', verbose_name='اندازه فونت زیرعنوان'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='text_position',
            field=models.CharField(choices=[('top-left', 'بالا چپ'), ('top-center', 'بالا وسط'), ('top-right', 'بالا راست'), ('center-left', 'وسط چپ'), ('center', 'وسط'), ('center-right', 'وسط راست'), ('bottom-left', 'پایین چپ'), ('bottom-center', 'پایین وسط'), ('bottom-right', 'پایین راست')], default='center', max_length=20, verbose_name='موقعیت متن'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='title_color',
            field=models.CharField(default='#ffffff', help_text='کد رنگ hex (مثال: #ffffff)', max_length=7, verbose_name='رنگ عنوان'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='title_font_size',
            field=models.PositiveIntegerField(default=30, help_text='اندازه فونت به پیکسل', verbose_name='اندازه فونت عنوان'),
        ),
    ]
