# Generated by Django 4.2.11 on 2025-09-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mainslider_button_text_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocard',
            name='text_position',
        ),
    ]
