# Generated by Django 4.2.11 on 2025-09-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_promocard_text_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocard',
            name='text_position',
            field=models.CharField(choices=[('top-left', 'بالا چپ'), ('top-center', 'بالا وسط'), ('top-right', 'بالا راست'), ('center-left', 'وسط چپ'), ('center', 'وسط'), ('center-right', 'وسط راست'), ('bottom-left', 'پایین چپ'), ('bottom-center', 'پایین وسط'), ('bottom-right', 'پایین راست')], default='center', max_length=20, verbose_name='موقعیت متن'),
        ),
    ]
