# Generated by Django 4.2.11 on 2025-09-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_promocard_text_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='text_position',
        ),
        migrations.RemoveField(
            model_name='promocard',
            name='text_position',
        ),
    ]
