# Generated by Django 5.1.4 on 2025-07-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_authority',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_ref_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='province',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='update_at',
        ),
    ]
