# Generated by Django 5.1.4 on 2025-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationalcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
